name: t_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.18.1
  logger: ^2.0.1
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0
  image_picker: ^1.1.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  # Fire base
  firebase_core: ^2.31.0
  cloud_firestore:  ^4.17.3
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1
  faker: ^2.1.0
  uuid: ^4.4.0
  firebase_app_check: ^0.2.2+7
  dart_style: ^2.3.6
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  auto_size_text: ^3.0.0
  dio: ^5.0.0
  flutter_dotenv: ^5.2.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^18.0.1
  app_settings: ^5.2.0
  googleapis_auth: ^1.6.0









  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/data/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800