// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm2AuVcI89Rsuf2D2kXvGRXPELgLh_kIQ',
    appId: '1:863763689183:web:f23bfd624ef63bda75036a',
    messagingSenderId: '863763689183',
    projectId: 'da-gr1',
    authDomain: 'da-gr1.firebaseapp.com',
    storageBucket: 'da-gr1.appspot.com',
    measurementId: 'G-528MJKQ2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CCXBzKHmYMrTf9502qO9Tm8ei3VG6h0',
    appId: '1:863763689183:android:973a22373a49f00f75036a',
    messagingSenderId: '863763689183',
    projectId: 'da-gr1',
    storageBucket: 'da-gr1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGd812cHt51ApMtb2WoDkERNfhINSjzp4',
    appId: '1:863763689183:ios:926d525548cdcddb75036a',
    messagingSenderId: '863763689183',
    projectId: 'da-gr1',
    storageBucket: 'da-gr1.appspot.com',
    androidClientId: '863763689183-6tfmcbmvkbgqn2f95lj0g57e55al1l9v.apps.googleusercontent.com',
    iosClientId: '863763689183-04aqeps9n9nd9l2675qm0dufjlcumrka.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGd812cHt51ApMtb2WoDkERNfhINSjzp4',
    appId: '1:863763689183:ios:926d525548cdcddb75036a',
    messagingSenderId: '863763689183',
    projectId: 'da-gr1',
    storageBucket: 'da-gr1.appspot.com',
    androidClientId: '863763689183-6tfmcbmvkbgqn2f95lj0g57e55al1l9v.apps.googleusercontent.com',
    iosClientId: '863763689183-04aqeps9n9nd9l2675qm0dufjlcumrka.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm2AuVcI89Rsuf2D2kXvGRXPELgLh_kIQ',
    appId: '1:863763689183:web:5faf873b80d5d8db75036a',
    messagingSenderId: '863763689183',
    projectId: 'da-gr1',
    authDomain: 'da-gr1.firebaseapp.com',
    storageBucket: 'da-gr1.appspot.com',
    measurementId: 'G-FL77R3YFLE',
  );

}