# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    abort("Unable to locate Flutter engine settings. Try running 'flutter pub get'")
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    if line =~ /FLUTTER_ROOT\=(.*)/
      return $1.strip
    end
  end
  abort("FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try running 'flutter pub get'")
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # Nếu dự án của bạn không yêu cầu dynamic frameworks, hãy bỏ qua use_frameworks!
  # Một số plugin có thể yêu cầu use_frameworks! nhưng thường Flutter được phân phối dưới dạng static.
  # Bạn có thể thử loại bỏ hoặc thêm lại nếu gặp vấn đề khác.
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
