# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    puts "Generated.xcconfig not found. Please run 'flutter pub get'"
    exit
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    if line =~ /FLUTTER_ROOT=(.*)/
      return $1.strip
    end
  end
  puts "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Please ensure that your Flutter environment is set up properly."
  exit
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup
